POST http://127.0.0.1:8000/api/v1/user/me
Content-Type: application/json, text/plain, */*
Authorization: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiN2UxOWNkNmIxYTFhN2Y3ZTZkODc2ZWFkZDk0NDQ5ZDA2MGU2M2IwYzNmM2U1ZTQ3YmI3ODQ4NmYwNTdjNWIyNTMxZjgwN2ZlMmJmYmQyZGEiLCJpYXQiOjE1OTk4MDUzNDAsIm5iZiI6MTU5OTgwNTM0MCwiZXhwIjoxNjE1NDQzNzQwLCJzdWIiOiI4Iiwic2NvcGVzIjpbXX0.vHohYAthAZS7BDpGbfnMiy87Tgc9T1czVd29Q5THdHsog455unbbPCRYHGe3cBX8LJPeIO7u1Y9w8Jd0z-mwH-Z1uzdGjdHjtqNIavvwfu9C9hhOZ-N9wZBXhLYMJ68_E5f4BoiVU1ALh1o7h7XWPreB5ZzP9bLt392AuP2ZBrknrOy0AxvaZInE0me6rG7hOyCKygMQrMxUrpNQvLHI7aLBHmp6_92XNKWm_O_9CYXqQ78MutZ00UIuP5NdohkH9ervUej037d0Sxl_hFw1NhG4u1MQamK0G6tYPIcutVZ2tMgdzspFVE11WLE9FanU80vUeZniF00iITcsdKMOqWRpY31tUmqXiQ6pZ8urb3iuCllWVh-qjA1TxqOSmyg64w3neqm2e6gthNpW7osXc96FdsRo0pfOpaqr_4qbep3dGWgApi-jdpJMP01tMlR1FWwe5Tl7elr2OrLGbxu8vK07M_jpIVzOYiV3xQZhckdbS0xO5K8M6AyM1geSkOenwB5spN1UQV4Js4qOq_pGj2K2zlAESmWru6Yq3_N7TaMsdTL5_ywwvQVjaMsjOmikUT_ps56l_RaKlF722WNRW9FcRZy6UmtCVS4gk5I3WF29FDvl2RAIjpyRU9pqcOyh35vdZ3oMS9kiEUuKuQNMCDxfk9RxenZjP7sfwRG1Ddc'
